version: '3.8'
services:
  postgres:
    image: 'postgres:latest'
    container_name: postgres
    restart: unless-stopped
    environment:
      - 'POSTGRES_DB=apuesta'
      - 'POSTGRES_PASSWORD=apuesta123'
      - 'POSTGRES_USER=apuesta'
    ports:
      - '15432:5432'
    volumes:
      - apuesta_postgres:/var/lib/postgresql/data
      - ./sql/tablas.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - apuesta_network

networks:
  apuesta_network:
    driver: bridge

volumes:
  apuesta_postgres:

